docs: Update release notes for tracker
dhis2/dhis2-releases pull request #103
Opened 2023-04-05 08:13 UTC by enricocolasante

2023-04-13 05:06 UTC, Bekkalizer requested changes
Looks good! Made some minor language suggestions.

2023-04-13 05:06 UTC, Bekkalizer commented on releases/2.40/README.md
> +* **Old tracker APIs deprecated:** In previous release old tracker API endpoints were deprecated. (see [deprecated-features](https://github.com/dhis2/dhis2-releases/blob/master/releases/deprecated-fe
```suggestion
* **Old tracker APIs deprecated:** In the previous release, the old tracker API endpoints were deprecated. (see [deprecated-features](https://github.com/dhis2/dhis2-releases/blob/master/releases/deprecated-features.md) ). We encourage developers of apps and extensions transition and move away from the old endpoints. The deprecated API endpoints are:
```

2023-04-13 05:06 UTC, Bekkalizer commented on releases/2.40/README.md
> +* **Removed status field in bundleReport:** Import summaries have the following overall structure [defined here](https://docs.dhis2.org/en/develop/using-the-api/dhis-core-version-240/tracker.html#imp
```suggestion
* **Removed the status field in bundleReport:** Import summaries have the following overall structure [defined here](https://docs.dhis2.org/en/develop/using-the-api/dhis-core-version-240/tracker.html#import-summary-structure). The status field in `bundleReport` property was redundant and hence it was removed. The `Status` field in the root of the import summary should be used instead.
```

2023-04-13 05:06 UTC, Bekkalizer commented on releases/deprecated-features.md
> +|Old tracker endpoints are deprecated, and replaced by `/api/tracker` endpoint |Sep 2022|2.41.0|
```suggestion
|The old tracker endpoints are deprecated and replaced by `/api/tracker` endpoint |Sep 2022|2.41.0|
```

2023-04-13 07:44 UTC, teleivo commented on releases/2.40/README.md
> +* **Old tracker APIs deprecated:** In previous release old tracker API endpoints were deprecated. (see [deprecated-features](https://github.com/dhis2/dhis2-releases/blob/master/releases/deprecated-fe
> **Old tracker APIs deprecated:** In previous release old tracker API endpoints were deprecated.

Did we miss adding this note in the last release? Or is it just a reminder?

I would replace `In previous release` with the exact version they were deprecated 😄

2023-04-13 07:44 UTC, teleivo commented on releases/2.40/README.md
> +   - /api/relationships
Are these all the old tracker endpoints? I wonder if there are some that exist in old tracker but were just not implemented in new tracker 🤔

2023-04-13 07:44 UTC, teleivo commented on releases/2.40/README.md
> +   This endpoint should be used instead:
Use [tracker endpoints](https://docs.dhis2.org/en/develop/using-the-api/dhis-core-version-240/tracker.html) instead.
```suggestion
   This endpoint should be used instead:
```

as you list endpoint**s** but then say use endpoint (singular) instead.

2023-04-18 12:20 UTC, teleivo approved these changes

2023-04-21 10:13 UTC, merged