docs: Document ACL org unit mode behavior [TECH-1590]
dhis2/dhis2-releases pull request #136
Opened 2023-11-15 13:34 UTC by muilpp

2023-11-15 14:02 UTC, enricocolasante requested changes

2023-11-15 14:02 UTC, enricocolasante commented on releases/2.41/README.md
> +#### ACL tracker export breaking changes
When describing a breaking change, it is important to make very clear what was the previous behavior and what is the current behavior.
In all the following points, it is clear what is the current behavior but without the description of the previous one, it is not so clear how it is a breaking change.

Additionally, would be good to reference the Jira ticket for each of the points if it makes sense.

2023-12-12 14:53 UTC, muilpp commented on releases/2.41/README.md
> +#### ACL tracker export breaking changes
it now reflects whether each change affects older versions or not

2023-12-12 15:19 UTC, enricocolasante reviewed
Just a comment on the status code vs exception naming.
Lets see what @Bekkalizer has to say on the sensitive point there

2023-12-12 15:19 UTC, enricocolasante commented on releases/2.41/README.md
> +    * [TECH-1656](https://dhis2.atlassian.net/browse/TECH-1656) A request to `/trackedEntities` will now result in a `ForbiddenException` if the user lacks access to the requested program or tracked
Yes, but maybe it is better to specify the HTTP code that the client will receive in the response.
The client won't see the type of exception.
I would also change in the other places `BadRequestException` with 400 response status code or something similar

2024-01-16 12:43 UTC, Bekkalizer commented on releases/2.41/README.md
> +    * [TECH-1589](https://dhis2.atlassian.net/browse/TECH-1589): In `/enrollments` and `/tracker/enrollments`, the organization unit mode `ALL` is now restricted to users with either `ALL` or `F_TRAC
Not sensitive as such - the user does not get access to more data. It does change the behavior for the API slightly, as we are now giving an error on calls that would not previously.

2024-01-16 12:47 UTC, Bekkalizer approved these changes

2024-01-19 14:38 UTC, enricocolasante approved these changes

2024-01-22 13:11 UTC, merged