docs: Implement cascading deletion for obsolete TrackedEntities[DHIS2-15066]
dhis2/dhis2-releases pull request #196
Opened 2024-12-05 09:02 UTC by zubaira

2024-12-05 11:23 UTC, enricocolasante commented on releases/2.42/migration-notes.md
> +       - [Null Tracked Entity Type](#null-tracked-entity-type)
```suggestion
       - [Null Organisation Unit](#null-organisation-unit)
       - [Null Tracked Entity Type](#null-tracked-entity-type)
```

2024-12-05 11:23 UTC, enricocolasante commented on releases/2.42/migration-notes.md
> +#### Fixing Null Values
As we are doing for null orgUnit, we should provide a way for the user to fix the data and put it as a first option.
Deleting data should be the last resort here.
What we did in the other section was to suggest to find a similar entity and to transfer the metadata from that entity to the inconsistent entity.

2024-12-11 13:20 UTC, enricocolasante requested changes

2024-12-11 13:20 UTC, enricocolasante commented on releases/2.42/migration-notes.md
> +```sql
Here we shouldn't show entities that we can fix in the migration, so we should filter out any tracked entity that has an enrollment with a program that has a defined trackedEntityType

2024-12-11 13:20 UTC, enricocolasante commented on releases/2.42/migration-notes.md
> +```sql
Same here

2024-12-11 13:20 UTC, enricocolasante commented on releases/2.42/migration-notes.md
> +To assign valid trackedentitytypeid. It can be fetched from program via enrollment.
This is what we are doing in the migration, we shouldn't let them doing here manually.
This section should be about the tracked entities that the migration wasn't able to fix, so we should provide a way, as naive as possible, to make them manually fix the data.
In the null organisation unit what I did was to make them find a similar event/enrollment and copy the organisation unit from there.

Here, as there shouldn't be so many tracked entity types in the system, we could provide a SQL snippet to let them assign one tracked entity type of their choose.

2024-12-11 13:20 UTC, enricocolasante commented on releases/2.42/migration-notes.md
> +The following script can be used to remove all trackedentities with null in `trackedentitytypeid` column.
Here we need to be really careful and make them notice that this SQL will remove all the tracked entities, even the ones that could potentially be fixed.

Maybe should we provide an alternative one that only remove the not automatically fixable tracked entity?

2024-12-20 11:05 UTC, enricocolasante commented on releases/2.42/migration-notes.md
> +##### Deleting invalid trackedenetities
```suggestion
##### Deleting invalid tracked entities
```

2024-12-20 11:05 UTC, enricocolasante commented on releases/2.42/migration-notes.md
> +```sql
I still think we should change this query to not show the entities that will be fixed by the migration

2024-12-20 11:05 UTC, enricocolasante commented on releases/2.42/migration-notes.md
> +```plsql
This script should remove only the entities that are not going to be fixed by the migration

2024-12-23 14:31 UTC, enricocolasante commented on releases/2.42/migration-notes.md
> +##### Deleting invalid tracked enetities
```suggestion
##### Deleting invalid tracked entities
```

2024-12-23 14:31 UTC, enricocolasante commented on releases/2.42/migration-notes.md
> +- Completely remove invalid trackedentity record. ([Delete trackedentities](#deleting-invalid-trackedenetities))
```suggestion
- Completely remove invalid trackedentity record. ([Delete trackedentities](#deleting-invalid-tracked-entities))
```

2024-12-23 14:31 UTC, enricocolasante commented on releases/2.42/migration-notes.md
> +  );
```suggestion
SELECT COUNT(1)
FROM trackedentity te
WHERE te.trackedentitytypeid IS NULL
  AND NOT EXISTS (
    SELECT 1
    FROM enrollment e JOIN program p on e.programid = p.programid
    WHERE e.trackedentityid = te.trackedentityid and p.trackedentitytypeid IS NOT NULL
);
```

2024-12-23 14:31 UTC, enricocolasante commented on releases/2.42/migration-notes.md
> +  );
```suggestion
SELECT COUNT(1)
FROM trackedentityinstance te
WHERE te.trackedentitytypeid IS NULL
  AND NOT EXISTS (
    SELECT 1
    FROM programinstance pi JOIN program p ON pi.programid = p.programid
    WHERE pi.trackedentityinstanceid = te.trackedentityinstanceid and p.trackedentitytypeid IS NOT NULL
  );
```

2024-12-23 14:31 UTC, enricocolasante commented on releases/2.42/migration-notes.md
> +UPDATE trackedentity SET trackedentitytypeid=( SELECT trackedentitytypeid FROM trackedentitytype WHERE uid='{REFERENCE_UID}') WHERE trackedentitytypeid IS NULL;
This query is changing all the trackedEntities with `null` tracked entity type at once.
Can we change the count queries to return the tracked entity uids to be fixed instead of just a count?
And then add them here as a parameter, like ` AND trackedentityid IN ({uids})`?

2024-12-23 14:31 UTC, enricocolasante commented on releases/2.42/migration-notes.md
> +            WHERE enrollment.trackedentityid = trackedentity.trackedentityid
```suggestion
            SELECT 1
            FROM enrollment e JOIN program p on e.programid = p.programid
            WHERE e.trackedentityid = te.trackedentityid and p.trackedentitytypeid IS NOT NULL
```

2025-01-06 10:07 UTC, zubaira commented on releases/2.42/migration-notes.md
> +            WHERE enrollment.trackedentityid = trackedentity.trackedentityid
fixed

2025-01-13 11:54 UTC, enricocolasante commented on releases/2.42/migration-notes.md
> +        WITH deleted AS (DELETE FROM trackedentity WHERE trackedentitytypeid IS NULL RETURNING *) SELECT COUNT(*) INTO deleted_count FROM deleted;
Here we should delete only the invalid tracked entities. Without the NOT EXISTS clause, also the fixable ones are going to be deleted

```suggestion
        WITH deleted AS (DELETE FROM trackedentity WHERE trackedentitytypeid IS NULL AND NOT EXISTS (
           SELECT 1
            FROM enrollment e JOIN program p on e.programid = p.programid
            WHERE e.trackedentityid = te.trackedentityid and p.trackedentitytypeid IS NOT NULL
        ) 
        RETURNING *) SELECT COUNT(*) INTO deleted_count FROM deleted;
```

2025-01-14 12:31 UTC, enricocolasante approved these changes

2025-01-16 06:20 UTC, merged