docs: removed JSONP for system settings [DHIS2-12516]
dhis2/dhis2-releases pull request #73
Opened 2022-02-23 10:38 UTC by jbee

2022-03-23 09:09 UTC, Philip-Larsen-Donnelly requested changes
Please confirm which patch this is included in and move to a patch-specific section similar to https://github.com/dhis2/dhis2-releases/tree/master/releases/2.35#patch-specific-changes

2022-03-24 13:03 UTC, jbee commented
@Philip-Larsen-Donnelly I moved it to a patch specific section - as far as I can tell the next release of 2.37 is 2.37.5 where it then should be included. Can you confirm that? I did check it was only merged to `2.37` branch.

2022-03-24 16:20 UTC, Philip-Larsen-Donnelly commented
> @Philip-Larsen-Donnelly I moved it to a patch specific section - as far as I can tell the next release of 2.37 is 2.37.5 where it then should be included. Can you confirm that? I did check it was only merged to `2.37` branch.

Yes, I confirm 2.37.5 is the next patch. (should always be the next unreleased one in the Fix Versions dropdown on the Jira issue).

2022-03-24 16:20 UTC, Philip-Larsen-Donnelly approved these changes

2022-03-24 16:20 UTC, merged